app:
  env: dev
  name: go-mall
  log:
    path: "/tmp/applog/go-mall.log"
    max_size: 1
    max_age: 60
  pagination:
    default_size: 20
    max_size: 100
db:
  type: mysql
  master:
    dsn: root:Wasd4044@tcp(127.0.0.1:3306)/go_mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
    max_open: 100
    max_idle: 10
    max_life_time: 5
  slave:
    dsn: root:Wasd4044@tcp(127.0.0.1:3306)/go_mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
    max_open: 100 # 100或200
    max_idle: 20 # max_open的25%-50%
    max_life_time: 5 # 连接空闲多久后关闭连接最大生命周期, 通常5-30分钟

redis:
  addr: 127.0.0.1:6379
  password: ""
  pool_size: 10
  db: 0